# Generated by Django 4.0.5 on 2022-06-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumeal',
            old_name='meal',
            new_name='meal_name',
        ),
    ]
