# Generated by Django 4.0.5 on 2022-06-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_meal_menumeal_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='category_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='meal_name_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='meal_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='meal_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='menu_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_meals', to='restaurant.menu'),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='menu_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_meals', to='restaurant.menu'),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='menu_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_meals', to='restaurant.menu'),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='price_az',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='price_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='menumeal',
            name='price_ru',
            field=models.FloatField(null=True),
        ),
    ]
