# Generated by Django 4.0.5 on 2022-06-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_menu_category_az_remove_menu_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumeal',
            name='menu_az',
        ),
        migrations.RemoveField(
            model_name='menumeal',
            name='menu_en',
        ),
        migrations.RemoveField(
            model_name='menumeal',
            name='menu_ru',
        ),
    ]
