# Generated by Django 4.0.5 on 2022-06-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_menumeal_menu_az_remove_menumeal_menu_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumeal',
            name='price_az',
        ),
        migrations.RemoveField(
            model_name='menumeal',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='menumeal',
            name='price_ru',
        ),
    ]
