# Generated by Django 4.0.5 on 2022-06-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_gallery_image_alter_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
