# Generated by Django 4.0.5 on 2022-06-23 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_gallery_image_alter_menu_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
