# Generated by Django 4.0.5 on 2022-06-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_menu_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
